name = animalworld
title = Wilhelmines Animal World
description = Adds various wild animals
depends = mobs
optional_depends = default, mcl_core, mcl_sounds, bucket, ethereal, xocean, farming, fishing, hunger_ng, livingcaves
min_minetest_version = 5.10
